### ISSUE TITLE
CARMA requires an additional node to handle motion prediction separate from object detection tracking

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#807]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Object detection and tracking currently converts autoware.ai messages into carma messages and applies motion prediction to those messages. This is a problem since the autoware messages do not contain predictions. In order to rectify this, a new node must be created to handle the motion prediction logic separately from object detection tracking. 
### Expected behavior
CARMA Platform should be able to receive autoware.ai messages and convert them into carma messages. Once the conversion is complete, the system should then output the external object information from those carma messages as well as the predictions from those messages.
### Software version this applies to
3.3.0

### Actual behavior
CARMA accepts autoware.ai messages as input and uses the logic in the object detection tracking node to convert them into carma messages. Once the external object information from these messages has been published to the associated /external_objects topic, the motion prediction node publishes the predictions from the carma message to another topic that connects to the roadway objects node.

**Comment by msmcconnell** [comment]
Resolved by above PR
