### ISSUE TITLE
Improve path tracking accuracy in trucks

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#997]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While testing the ACE demo, both the Red and White trucks demonstrated some oscillation in their path following with each occasionally straying into the adjacent lane. The motion does not appear to be excessive and is probably acceptable for the ace demo, however, if time permits we should continue trying to improve it. An acceptable performance would have the vehicle only crossing into the other lane 3 times before the lane change and never by more than a tire width. 

### Carma version where this issue was discovered

release/Wanderer
### Expected behavior
Truck tracks lane accurately and does not enter other lane. 
### Actual behavior

Trucks show oscillatory behavior that will cross into the other lane slightly but with a frequency large enough to be noticed. 
### Steps to reproduce the actual behavior

Run carma with GPS mode and follow the ACE demo route.
